stages:
  - build
  - lint

variables:
  APT_CACHE_DIR: ${CI_PROJECT_DIR}/.cache/apt
  CATKIN_DIR: ${CI_PROJECT_DIR}/catkin
  SECOND_REPO_PATH: stephan.rediske/universal_robot
  THIRD_REPO_PATH: stephan.rediske/robotiq

default:
  image: docker.zal.aero/zal/topics/docker/ros:noetic-ros-base
  retry:
    max: 1
    when: always
  cache:
    paths:
      - .cache/
      - catkin/
  before_script:
    - rm -f /etc/apt/apt.conf.d/docker-clean
    - echo -e "APT::Archives::MaxAge "'"7"'";\nAPT::Archives::MinAge "'"2"'";\nAPT::Archives::MaxSize "'"2000"'";\nDir::Cache::Archives "'"'"${APT_CACHE_DIR}"'"'";" >> /etc/apt/apt.conf.d/20archive
    - mkdir -p ${APT_CACHE_DIR}
    - dpkg --force-all -i ${APT_CACHE_DIR}/*.deb
    - apt-get install -f -y

install dependencies:
  stage: .pre
  before_script:
    - rm -f /etc/apt/apt.conf.d/docker-clean
    - echo -e "APT::Archives::MaxAge "'"7"'";\nAPT::Archives::MinAge "'"2"'";\nAPT::Archives::MaxSize "'"2000"'";\nDir::Cache::Archives "'"'"$APT_CACHE_DIR"'"'";" >> /etc/apt/apt.conf.d/20archive
    - rm -rf catkin
    - shopt -s extglob
    - mkdir ${CI_PROJECT_NAME} && mv !(catkin|apt|${CI_PROJECT_NAME}) ${CI_PROJECT_NAME}
    - git clone $(echo ${CI_REPOSITORY_URL} | sed -e s"|${CI_PROJECT_PATH}|${SECOND_REPO_PATH}|")
    - git clone $(echo ${CI_REPOSITORY_URL} | sed -e s"|${CI_PROJECT_PATH}|${THIRD_REPO_PATH}|")
    - mkdir -p ${CATKIN_DIR}/src && mv !(catkin|apt) ${CATKIN_DIR}/src
    - mkdir -p ${APT_CACHE_DIR} ; mv /var/cache/apt/archives/* ${APT_CACHE_DIR} -f
    - apt-get update
    - apt-get install -y catkin-lint
  script:
    - rosdep update
    - rosdep install --from-paths catkin/src --ignore-src -r -y
  after_script:
    - shopt -s extglob

catkin build:
  stage: build
  script:
    - catkin config --init --extend /opt/ros/noetic --workspace catkin
    - catkin build --summarize --no-status --force-color --workspace catkin

catkin lint:
  stage: lint
  allow_failure: true
  script:
    - source catkin/devel/setup.bash
    - catkin_lint -W2 catkin/src/${CI_PROJECT_NAME} | tee catkin_lint.txt
  artifacts:
    name: catkin_lint
    when: always
    paths:
      - catkin_lint.txt
    expire_in: 1 week
